### PR TITLE
Added full documentation on dola_t5, ifeval and memotrap scripts

### PR DESCRIPTION
**Pull request by felipejinli**
I've added documentation of the entire repository and the main code files.
To improve the usability of the repository for readers who want to reproduce our experiments more easily.

@itshuey Can you give this a look and merge if happy?

### CODE REVIEW

**Comment by itshuey** [comment]
Thanks @felipejinli. The content looks good, but there seems to be some unintended line breaks when I preview the README [on your fork](https://github.com/felipejinli/DoLa/tree/main?tab=readme-ov-file#main-files-with-detailed-docs). Could you check on this? 

Also, I've just [uploaded the results](https://github.com/itshuey/DoLa/tree/main/results) from our work, including the model outputs, the evaluations of the outputs, and our logit analysis. Do you mind adding a brief section about this at the end that we can link for readers?

**Comment by felipejinli** [comment]
@itshuey added refactoring of dola_t5 (c3dcd35) with following changes:

- error handling on model loading particularly if tokenizer fails to load
- introduced proper logging w diff severity levels
- adopted python type hints for future maintainability

**Comment by felipejinli** [comment]
> Thanks @felipejinli. The content looks good, but there seems to be some unintended line breaks when I preview the README [on your fork](https://github.com/felipejinli/DoLa/tree/main?tab=readme-ov-file#main-files-with-detailed-docs). Could you check on this?
> 
> Also, I've just [uploaded the results](https://github.com/itshuey/DoLa/tree/main/results) from our work, including the model outputs, the evaluations of the outputs, and our logit analysis. Do you mind adding a brief section about this at the end that we can link for readers?

@itshuey Yes will do this now. Also will create a separate PR for the refactoring of dola_t5 and depollute this PR commit

Figured out the culprit it's due to [non-breaking spaces](https://stackoverflow.com/questions/15721373/how-do-i-ensure-that-whitespace-is-preserved-in-markdown) - will fix with new commit.

**Comment by felipejinli** [comment]
@itshuey Just finished making the changes. Can you give it a check?

**Comment by itshuey** [comment]
LGTM! Thanks for adding this documentation.

**Pull request merged**
